Enhance GitHub Actions workflow to build Docker image and create release with version extraction

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build Docker image
+name: Build Docker image and Create Release
 
 on:
     push:
@@ -7,15 +7,31 @@ on:
 
 env:
     REGISTRY: ghcr.io
-    IMAGE_NAME: ${{ github.repository }}
+    REPOSITORY: ${{ github.repository }}
 
 jobs:
+    get-version:
+        runs-on: ubuntu-24.04
+        outputs:
+            version: ${{ steps.get_version.outputs.version }}
+
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
+
+            - name: Get Version from package.json
+              id: get_version
+              run: |
+                  version=$(jq -r .version package.json)
+                  echo "Version from package.json: $version"
+                  echo "version=$version" >> $GITHUB_OUTPUT
+
     build:
-        runs-on: ubuntu-latest
+        needs: get-version
+        runs-on: ubuntu-24.04
         permissions:
-            contents: write
+            contents: read
             packages: write
-            issues: write
 
         steps:
             - name: Checkout repository
@@ -23,6 +39,8 @@ jobs:
 
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
+              with:
+                  install: true
 
             - name: Log into registry ${{ env.REGISTRY }}
               uses: docker/login-action@v3
@@ -31,66 +49,59 @@ jobs:
                   username: ${{ github.actor }}
                   password: ${{ secrets.GITHUB_TOKEN }}
 
-            - name: Get Version from setup.py
-              id: get_version
-              run: |
-                  version=$(grep 'version=' setup.py | sed -E "s/.*version=['\"]([^'\"]+)['\"].*/\\1/")
-                  echo "version: $version"
-                  echo "version=$version" >> $GITHUB_ENV
-
-            - name: Check and create release
-              id: check_release
-              run: |
-                  # Check if the release exists
-                  release_exists=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                    -H "Accept: application/vnd.github+json" \
-                    https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.version }} | jq -r .message)
-
-                  if [[ "$release_exists" == "Not Found" ]]; then
-                      echo "Creating release for version ${{ env.version }}..."
-                      curl -s -X POST \
-                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                        -H "Accept: application/vnd.github+json" \
-                        https://api.github.com/repos/${{ github.repository }}/releases \
-                        -d "{
-                              \"tag_name\": \"${{ env.version }}\",
-                              \"target_commitish\": \"master\",
-                              \"name\": \"${{ env.version }}\",
-                              \"body\": \"Description of the release\",
-                              \"draft\": false,
-                              \"prerelease\": false
-                            }"
-                  else
-                      echo "Release already exists for version ${{ env.version }}."
-                  fi
-
-            - name: Get Latest Release
-              id: get_release
-              run: |
-                  latest_release=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                  https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .name)
-                  echo "Latest release: $latest_release"
-                  echo "latest_release=$latest_release" >> $GITHUB_ENV
+            - name: Echo version
+              run: echo "Building ${{ env.REGISTRY }}/${{ env.REPOSITORY }}, version ${{ needs.get-version.outputs.version }}"
 
             - name: Extract Docker metadata
               id: meta
               uses: docker/metadata-action@v5
               with:
-                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+                  images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
                   tags: |
                       latest,
-                      ${{ env.latest_release }},
-                      ${{ env.version }}
-
-            - name: Echo tags
-              run: echo ${{ steps.meta.outputs.tags }}
+                      ${{ needs.get-version.outputs.version }}
 
             - name: Build and push Docker image
               uses: docker/build-push-action@v5
               with:
                   context: .
                   push: true
-                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }} , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.latest_release }}
+                  tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest,${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ needs.get-version.outputs.version }}
                   labels: ${{ steps.meta.outputs.labels }}
                   cache-from: type=gha
                   cache-to: type=gha,mode=max
+
+    create-release:
+        needs: [get-version, build]
+        runs-on: ubuntu-24.04
+        permissions:
+            contents: write
+
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
+
+            - name: Set up GitHub CLI
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 22
+
+            - name: Create Release
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              run: |
+                  version="${{ needs.get-version.outputs.version }}"
+
+                  if ! gh release create "$version" \
+                    --repo="${{ github.repository }}" \
+                    --title="$version" \
+                    --generate-notes; then
+                    
+                    if gh release view "$version" --repo ${{ github.repository }} &>/dev/null; then
+                      echo "Release $version already exists, treating as success"
+                      exit 0
+                    else
+                      echo "Failed to create release and release doesn't exist"
+                      exit 1
+                    fi
+                  fi
